name: customMobs
description: Create custom mobs.
author: Mark
version: 1.0
main: customMobs.Main
commands:
   createMob:
      description: Create a mob
      usage: /createMob
   damageOn:
      description: Toggle damage for select entity on
      usage: /damageOn
   damageOff:
      description: Toggle damage for select entity off
      usage: /damageOff
   armor:
      description: Give a mob armor or remove it
      usage: /armor
   freeze:
      description: Freeze a mob
      usage: /freeze
   unfreeze:
      description: Unfreeze a mob
      usage: /unfreeze
   rename:
      description: Rename a mob
      usage: /rename	
   nameon:
      description: Toggle entity name on
      usage: /nameon
   nameoff:
      description: Toggle entity name off
      usage: /nameoff
   entities:
      description: List all entities and their id
      usage: /entities	
   equip:
      description: Equip an entity with an item
      usage: /equip
   deletemob:
      description: Remove a mob from the world
      usage: /deletemob
      
